### PR TITLE
initial xenial support

### PR DESCRIPTION
**Pull request by olegabr**
basic multi-distribution support added

Now files in `ubuntu/trusty/bin` and `ubuntu/xenial/bin` are the same, and it may confuse, but the is no reason they _must_ be the same. They can become different one day, just because it is different distribution versions.
Another reason is that `docker` requires all files used in building process to be in the same directory as the `Dockerfile` itself. You can see this style with a lot of file duplications in many repositories under the official-images umbrella.

### CODE REVIEW

**Comment by kylemanna** [comment]
As commented in #26, I don't see any value in maintaining backwards compatibility with 14.04.  The goal of this Docker repo is to have simple self contained image with a minimal number of permutations and hence things that can go wrong.  What's the use case for ever running future versions of bitcoind on 14.04?

Some of the other official docker repos are bases and need to support many versions hence the needed complexity.

Ultimately, I'd be curious to see if Alpine is a viable base image because of how lean it is compared to Ubuntu 16.04.  The upside to 16.04 is that it will have a long support life cycle and has lots of attention.

**Comment by olegabr** [comment]
Do you mean that I should just replace trusty with xenial?

**Comment by kylemanna** [comment]
I don't see why not, right?  Can you send a PR with that change after a quick test?

**Comment by olegabr** [comment]
see #38

**Pull request closed without merging**
