### PR TITLE
release: Bump to v22.0

### LINKED ISSUE #90: version 22.0
https://github.com/bitcoin/bitcoin/commits/22.x
not that it blocks anyone from working with bitcoin but an update for the docker to v22 would be nice

### PR DESCRIPTION
**Pull request by kylemanna**
* Update signing key and verification method as the hashes are now
  signed with many keys and fetching _all_ of them seems overkill.

Closes #90

### CODE REVIEW

**Comment by kylemanna** [comment]
Looking for testers to build and confirm this works. Thanks!

**Comment by schildbach** [comment]
I just built the docker image, and checked the SHA-256 of `/usr/local/bin/bitcoind` within the image is `4aebceb3caf83f27bd3dd9030da637bacc836912a65a896860dc0252d0ebfad9`. Then, I manually downloaded, verified and extracted Bitcoin Core 22.0 (x86_64-linux) from https://bitcoincore.org/en/download/ and its binary yields the same SHA-256.

I didn't actually _run_ the docker image yet, except for a quick `bitcoind --version` smoke test.

**Comment by turcane** [comment]
When getting it from dockerhub it's still 21.0.
https://registry.hub.docker.com/r/kylemanna/bitcoind/tags?page=1&ordering=last_updated

**Comment by dasilvatek** [comment]
@kylemanna thank you, I have tested and confirm this Dockerfile is working - please commit #91 to master. 

FYI @turcane this is how I tested:
1) git clone https://github.com/kylemanna/docker-bitcoind.git
2) cd docker-bitcoind/
3) wget https://github.com/kylemanna/docker-bitcoind/blob/5e11a9f1e48017a8563eea495014f19310426883/Dockerfile
4) docker build -t kylemanna/bitcoind:dev .
5) docker run [....] --name bitcoin-node-dev kylemanna/bitcoind:dev
6) docker exec -it bitcoin-node-dev bash -l
7) sha256sum /usr/local/bin/bitcoind
    4aebceb3caf83f27bd3dd9030da637bacc836912a65a896860dc0252d0ebfad9    /usr/local/bin/bitcoind
8) bitcoin-cli getnetworkinfo
    "version":  220000,
    "subversion":  "/Satoshi:22.0.0/",
    "protocolversion":  70016,
9) bitcoin-cli getblockchaininfo
    "chain":  "main",
    "blocks":  709078,

**Comment by schildbach** [comment]
I've now run it for a couple of weeks, including the new feature I2P, and it seems to work fine from what I can tell.

**Comment by kylemanna** [comment]
Merged and pushed the updated image. Thanks all. LMK if you see any issues.

**Pull request merged**
