### PR TITLE
added USER_ID and GROUP_ID build arguments to make it easier to run t…

### PR DESCRIPTION
**Pull request by andyichr**
Thanks for maintaining this docker image. I made a few small changes to improve security by allowing the group and user ids to be specified using docker build args, and documented this in the README.md.

### CODE REVIEW

**Comment by kylemanna** [comment]
How does changing the user or group IDs inside a container change security?

**Comment by andyichr** [comment]
Without using user namespaces, the users in the container have the same privs as on the host. Therefore, the default uid/gid (1000/1000) will have the same privs as that user on the host, which a lot of times is the first user added. The docker run command allows specifying the uid/gid when the container is started. Take this command for example:

    docker run --restart=always -v /data/Bitcoin:/bitcoin --name=bitcoind-node -d -p 8333:8333 -p 127.0.0.1:8332:8332 -u $( id -u bitcoind ):$( id -g bitcoind ) bitcoind:0.12.1

If the corresponding uid/gid does not exist inside the container, then this command will fail. The proposed change allows that uid/gid to be set for the docker user/group when the container is built, thus it exists and the above command works.

**Comment by andyichr** [comment]
To further clarify, it is a known security flaw in docker that users inside the container have equivalent privs on the host. E.g. root in the container is root on the host, uid 1000 in the container is uid 1000 on the host. If we have an actual user 1000 on the host, we probably don't want to run bitcoind as 1000 because we'd inadvertently be giving bitcoind the same privileges as uid 1000 on the host. User namespaces would be another approach to fixing this problem, e.g. mapping uid 0/root and uid 1000/bitcoin to some unpriv user on the host, but with the current state of docker, that's not nearly as simple as ensuring the same uid exists inside and out of the container, and starting the daemon explicitly as that user.

**Comment by kylemanna** [comment]
Gotcha.  Makes sense but seems like an extreme unlikely security risk for a remote compromise of bitcoind and a simultaneous internal compromise of Linux control groups Docker uses.  But, doesn't hurt.

I have one request though: Can you remove the `README.md` modifications and create a `build.md` document or similar under the `docs` directory and separate the commits?  See the `CONTRIBUTING.md` document for a brief overview.

**Comment by andyichr** [comment]
Sure thing. Just pushed the separated docs/commits.

**Comment by kylemanna** [comment]
Thanks!

**Pull request merged**
