### PR TITLE
Document environment variables usage

### PR DESCRIPTION
**Pull request by olegabr**
And a code snippet to use completely custom bitcoin.conf configuration file.

### CODE REVIEW

**Comment by kylemanna** [comment]
Can you tweak this pull request to keep the non-essential features like env variables in a markdown file under `docs`?

The goal is to keep the `README` as concise as possible and put the additional functions under `docs` for advanced use cases.

With that tweak I'd love to merge the doc update.

**Comment by olegabr** [comment]
My typical use-case with hub.docker.com is to search for some image and read the doc on the page that is published on the hub. Then I just choose the one where I can just copy-n-paste example for `docker` command, or, better, the whole workable `docker-compose.yml` file.
It should be very special case when I would go to the repository, then to the docs and find some examples.
The `README.md` is a marketplace for docker image. Must use it to attract new users.

**Comment by kylemanna** [comment]
The goal of the `README.md` is to be simple to follow and understand.  It can't explain everything, hence the docs directory.

**Comment by olegabr** [comment]
see #39

**Pull request closed without merging**
