### PR TITLE
Add insight to the docker image

### PR DESCRIPTION
**Pull request by kobigurk**
This adds the useful insight dashboard, that reads data directly from the leveldb files and allow you to query the blockchain.
I'm certain we don't want to merge it like this, maybe make it an option.
Your take?

### CODE REVIEW

**Comment by kylemanna** [comment]
I like the idea!

I think the best way to do this would be run an independent insight docker container that communicates with the bitcoind container.  That way people who just want bitcoind get that and nothing more.  People who want more can turn on insight when they want to.

**Comment by kylemanna** [comment]
The notion of multiple daemons in the same Docker container has always felt wrong, and bash really isn't a process monitor.  What if npm/node.js dies?  Who will restart it? The error won't get bubbled up to the Docker container level.

If insight was it's own Docker application / container then all these things would resolve themselves and the only annoying issue would be port forwarding and container orchestration, but I think that has gotten significantly better recently thanks to things like [Docker Compose](https://docs.docker.com/compose/)

**Comment by kobigurk** [comment]
Thanks for the comments! I'll give it some thought.

**Comment by kobigurk** [comment]
Followed your advice, take a look!

**Comment by kylemanna** [comment]
Took a peak and I like it!  There are far to many unrelated changes (i.e. README and repo names) to merge at this point.  If you could rebase and slim it down to the minimum that adds insight features, then I think it works and I can test and merge it!

The init script won't work as you expect since the script section is blocking, the other docker container will never start.  I'd recommend a separate init script in the insight folder for those who want to run insight.

**Comment by kobigurk** [comment]
Sure, I can remove the README.
The repo changes are mostly fixes to the rpc part. For example, "rpcallowip" doesn't accept "*" any more.

**Comment by Levino** [comment]
I hope the idea of this docker container is NOT to be a standalone "bitcoin server", but actually something that docker was designed for. Namely "bitcoind as a microservice". It should only run a bitcoind. Done. Preferably not even one single unnecessary application is installed and if you need additional services, link this bitcoind container to the other applications.

**Pull request closed without merging**
