### PR TITLE
release: Bump to v0.21.1

### PR DESCRIPTION
**Pull request by kylemanna**
Needs some quick testing. This enables taproot.

### CODE REVIEW

**Comment by schildbach** [comment]
Can this work? The binaries are not released yet, so they can't be downloaded.

I wonder why does this Docker image not build from source?

**Comment by kylemanna** [comment]
> Can this work? The binaries are not released yet, so they can't be downloaded.

The binaries were released days ago.  Review the `Dockerfile`. 

> I wonder why does this Docker image not build from source?

Because if built from source more people will come here and ask questions like this because the process will be even more complicated as we have to install the compilers and libraries.  And even then we'll have to verify the integrity of the source code (a PGP signature) and increase the scope of concern to all the tools included to build the source code.

The PGP signatures of the binaries are verified using the published Bitcon Core public key. Please review the `Dockerfile`.

Nearly half of the DockerFile is dedicated to verifying the authenticity of the downloaded binaries.

**Comment by kylemanna** [comment]
Looking for people to test this and I can merge it.

**Comment by alixanc** [comment]
(I have no idea what I'm doing but) I switched to /dev on my Synology/Docker full-node and 0.21.1 works perfectly so far, if that's of any help.

**Comment by Unreal1david** [comment]
> Looking for people to test this and I can merge it.

Running dev branch with no issues

**Pull request merged**
