### PR TITLE
ubuntu/xenial support and travis ci testing

### PR DESCRIPTION
**Pull request by olegabr**
The travis ci testing technique is copied from official repositories. It is proved to work: https://travis-ci.org/olegabr/docker-bitcoind/builds/141587226

### CODE REVIEW

**Comment by kylemanna** [comment]
Hi, thanks for the pull request, we should certainly upgrade to 16.04 at some point, but  I have some concerns though.

What's the motivation for copying all the files and burying them under another directory to support 16.04? It makes it more difficult to manager, diff, resolve bugs on etc.  The primary motivation of docker is to not care about what the underlying base distribution is, so we should take a stand and support only one.  Moving to 16.04 Xenial makes sense in this regard.

The Travis-CI integration is good and welcome!  However, it needs to be broken out to a separate commit and pull requests.  Ideally pull-requests (and to some degree commits) should be focused atomic features.  This is partly my fault for not putting together a contributing guide to highlight this.

**Comment by kylemanna** [comment]
I've added a [contributing guide](https://github.com/kylemanna/docker-bitcoind/blob/master/CONTRIBUTING.md).

Can you break out your travis-ci work and submit a new pull request with just those changes on the existing 14.04 build?  I'd love to get that integrated.

Following the merge of travis-ci testing we can explore moving to 16.04, best way to do this is probably create a xenial branch that will ultimately get merged with master after some testing.

**Comment by olegabr** [comment]
Thank you for your interest!
The PR for travis support is there: #27 
Please, see this discussion about different distributions support here: https://github.com/docker-library/memcached/pull/9
Basically, there are two reasons I can see here:
1. Security. It is safer to have only one baseimage for all your docker services
2. Legacy services. We have an already working system on, say, ubuntu. Now we want to move the infrastructure to the docker. And what we see here? Literally every image uses it's own baseimage distro. It means that to move to docker, we need to adopt our configuration files and may be do some other unpredictable changes to the already working code. Take into account that we have no administering and security specialists in distributions other than, say, ubuntu. As a result, we have an additional entry threshold to the docker. My solution to this problem is equivalent support for different distros, but I'm open to other suggestions.

I will close this PR and open another one after #27 merge.

**Comment by olegabr** [comment]
See the #28

**Pull request closed without merging**
